var BODYPART_COST = {
    [MOVE]:   50,
    [WORK]:   100,
    [CARRY]:  50,
    [ATTACK]: 80,
    [RANGED_ATTACK]: 150,
    [HEAL]:   200,
    [TOUGH]:  10,
    [CLAIM]:  600,
};

function bodyCost(body) {
    var total = 0;
    for (var i = 0; i < body.length; i++) {
        total += BODYPART_COST[body[i]] || 0;
    }
    return total;
}

var MINER_BODIES = {
    200:  [WORK, MOVE],
    300:  [WORK, WORK, MOVE],
    550:  [WORK, WORK, WORK, WORK, WORK, MOVE, MOVE],
    800:  [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, MOVE, MOVE],
    1300: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, MOVE, MOVE, MOVE],
    1800: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, MOVE, MOVE, MOVE],
    2300: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, MOVE, MOVE, MOVE],
    5600: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, MOVE, MOVE, MOVE, MOVE, MOVE],
};

var HAULER_BODIES = {
    200:  [CARRY, MOVE],
    300:  [CARRY, CARRY, MOVE, MOVE],
    550:  [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
    800:  [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
    1300: [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    1800: [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    2300: [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    5600: [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
};

var HARVESTER_BODIES = {
    200:  [WORK, CARRY, MOVE],
    300:  [WORK, CARRY, CARRY, MOVE, MOVE],
    400:  [WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
    550:  [WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE],
    800:  [WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE],
    1300: [WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    1800: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
};

var UPGRADER_BODIES = {
    200:  [WORK, CARRY, MOVE],
    300:  [WORK, CARRY, CARRY, MOVE, MOVE],
    550:  [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE],
    800:  [WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE],
    1300: [WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    1800: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    2300: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    5600: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
};

var FIGHTER_BODIES = {
    720:  [TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK],
    1300: [TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK],
    2000: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK],
};

var HEALER_BODIES = {
    720:  [TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL],
    1300: [TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL],
    2000: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL, HEAL],
};

var BUILDER_BODIES = {
    200:  [WORK, CARRY, MOVE],
    300:  [WORK, CARRY, CARRY, MOVE, MOVE],
    400:  [WORK, WORK, CARRY, CARRY, MOVE, MOVE],
    550:  [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE, MOVE],
    800:  [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
    1300: [WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    1800: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    2300: [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
};

var BODIES = {
    miner:    MINER_BODIES,
    hauler:   HAULER_BODIES,
    harvester:HARVESTER_BODIES,
    upgrader: UPGRADER_BODIES,
    fighter:  FIGHTER_BODIES,
    healer:   HEALER_BODIES,
    builder:  BUILDER_BODIES,
};

function bestBodyForAvailable(role, capacity, available) {
    return bestBodyForCapacity(role, Math.min(capacity, available));
}

function bestBodyForCapacity(role, capacity) {
    var table = BODIES[role];
    if (!table) return null;
    var keys = Object.keys(table).map(Number).sort(function (a, b) { return a - b; });
    var chosenKey = null;
    for (var i = 0; i < keys.length; i++) {
        if (keys[i] <= capacity) chosenKey = keys[i];
        else break;
    }
    if (chosenKey === null) return null;
    return { body: table[chosenKey], cost: chosenKey, role: role };
}

function bodySummary() {
    return {
        miner: Object.keys(MINER_BODIES).map(Number),
        hauler: Object.keys(HAULER_BODIES).map(Number),
        harvester: Object.keys(HARVESTER_BODIES).map(Number),
        upgrader: Object.keys(UPGRADER_BODIES).map(Number),
        fighter: Object.keys(FIGHTER_BODIES).map(Number),
        healer: Object.keys(HEALER_BODIES).map(Number),
        builder: Object.keys(BUILDER_BODIES).map(Number),
    };
}

module.exports = {
    bestBodyForAvailable: bestBodyForAvailable,
    bodyCost: bodyCost,
    bodySummary: bodySummary,
    BODIES: BODIES,
};
