'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const SRC = path.join(ROOT, 'src');
const ROOT_MAIN = path.join(ROOT, 'main.js');

function rimraf(dir) {
    if (!fs.existsSync(dir)) return;
    fs.rmSync(dir, { recursive: true, force: true });
}

function collectFiles(dir) {
    const out = [];
    const entries = fs.readdirSync(dir);
    for (let i = 0; i < entries.length; i++) {
        const entry = entries[i];
        const full = path.join(dir, entry);
        const stat = fs.statSync(full);
        if (stat.isDirectory()) {
            out.push.apply(out, collectFiles(full));
        } else if (entry.endsWith('.js')) {
            out.push(full);
        }
    }
    return out;
}

function moduleKey(filePath) {
    const relative = path.relative(SRC, filePath).replace(/\\/g, '/');
    return relative.replace(/\.js$/, '');
}

function bundle() {
    rimraf(DIST);
    fs.mkdirSync(DIST, { recursive: true });

    const files = collectFiles(SRC);
    const parts = [];

    parts.push('// Bundled Screeps AI — generated by scripts/build.js');
    parts.push('var __modules__ = {};');
    parts.push('function __require__(id, relativeTo) {');
    parts.push('    if (id.charAt(0) === \'.\') {');
    parts.push('        var base = relativeTo.split(\'/\');');
    parts.push('        base.pop();');
    parts.push('        var segs = id.split(\'/\');');
    parts.push('        for (var i = 0; i < segs.length; i++) {');
    parts.push('            var seg = segs[i];');
    parts.push('            if (seg === \'.\') { continue; }');
    parts.push('            if (seg === \'..\') { base.pop(); continue; }');
    parts.push('            base.push(seg);');
    parts.push('        }');
    parts.push('        id = base.join(\'/\');');
    parts.push('    }');
    parts.push('    if (!__modules__.hasOwnProperty(id)) {');
    parts.push('        throw new Error("Unknown module \'" + id + "\'");');
    parts.push('    }');
    parts.push('    var m = __modules__[id];');
    parts.push('    if (!m.loaded) {');
    parts.push('        m.exports = {};');
    parts.push('        m.fn.call(m.exports, function (rel) { return __require__(rel, id); }, m, m.exports);');
    parts.push('        m.loaded = true;');
    parts.push('    }');
    parts.push('    return m.exports;');
    parts.push('}');

    for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const key = moduleKey(file);
        const source = fs.readFileSync(file, 'utf8');
        parts.push('__modules__["' + key + '"] = {');
        parts.push('    loaded: false,');
        parts.push('    exports: {},');
        parts.push('    fn: function (require, module, exports) {');
        parts.push(source);
        parts.push('    }');
        parts.push('};');
    }

    const rootMain = fs.readFileSync(ROOT_MAIN, 'utf8');
    const entry = rootMain.replace(/require\(['"]\.\/src\/main['"]\)/g, '__require__("main", "main")');
    parts.push(entry);

    const outPath = path.join(DIST, 'main.js');
    fs.writeFileSync(outPath, parts.join('\n'));
    console.log('Built ' + outPath + ' (' + files.length + ' modules)');
}

if (require.main === module) {
    bundle();
}

module.exports = bundle;
